version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    command: --api --docker --docker.swarmmode
    ports:
    - "8080:8080"
    networks:
      - proxy
    labels:
      - "traefik.backend.loadbalancer.method=drr"
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == manager
  server:
    image: hnatekmar/server:v3
    build: .
    networks:
      - proxy
    deploy:
      mode: global
      labels:
        traefik.enable: "true"
        traefik.port: 3000
