version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    command: --api --docker --docker.swarmmode
    ports:
    - "80:80"
    - "8080:8080"
    networks:
      - proxy
    labels:
      - "traefik.backend.loadbalancer.method=drr"
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == manager
  server:
    image: hnatekmar/server:v3
    build: .
    networks:
      - proxy
    deploy:
      mode: global
      placement:
              constraints:
                      - node.role == worker
      labels:
              - "traefik.backend.loadbalancer.method=drr"
              - "traefik.frontend.rule=Method:POST"
              - "traefik.enable=true"
              - "traefik.docker.network=proxy"
              - "traefik.port=3000"
networks:
        proxy:
