version: '3'

services:
  server:
    image: hnatekmar/server:v4
    build: .
    depends_on:
      - redis
    env_file:
    - config.env
    networks:
      - proxy
    deploy:
      mode: global
      placement:
              constraints:
                      - node.role == worker
networks:
        proxy:
