{
 "title": "Best fitness",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "config_id",
    "label": "{.*}",
    "query": "SELECT id FROM \"Configurations\""
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "config_id" },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT config FROM \"Configurations\"\nWHERE \"id\" IN ($config_id)"
    }
   ]
  },
  {
   "title": "Best fitness per generation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"updatedAt\"),\n  \"maximum\",\n  \"minimum\"\nFROM\n  \"Generations\"\nWHERE\n  $__timeFilter(\"updatedAt\") AND \n  \"ConfigurationId\" IN ($config_id)\nORDER BY \"updatedAt\""
    }
   ]
  },
  { "title": "Configuration $config_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "config_id" },
  {
   "title": "Number of generations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  \"Generations\"\nWHERE\n  $__timeFilter(\"updatedAt\") AND \"ConfigurationId\" IN ($config_id)\n"
    }
   ]
  },
  {
   "title": "Best genome",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  best\nFROM\n  \"Generations\"\nWHERE\n  $__timeFilter(\"updatedAt\") AND\n  \"ConfigurationId\" IN ($config_id)\nORDER BY \"maximum\" DESC LIMIT 1"
    }
   ]
  }
 ]
}